
name: CraftBeerPi
version: 4.0.8

index_url: /cbpi_ui/static/index.html

port: 8000

mqtt: true
mqtt_host: mqtt
mqtt_port: 1883
mqtt_username: craftbeerpi
mqtt_password: cbpiSuperSecMq77!

username: cbpi
password: 123

plugins:
- cbpi4ui

